credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: ansible-tower-jenkins-user
              username: "satqe_auto_droid"
              password: ${casc-secret/tower-password} # This is stored in and loaded from OpenShift env as a Secrets obj.
              description: "Username/Password Credentials for Ansible Tower"
          - usernamePassword:
              scope: GLOBAL
              id: gitlab-jenkins-user
              username: "satqe_gitlab_jenkins_token"
              password: ${casc-secret/jenkins-token} # This is stored in and loaded from OpenShift env as a Secrets obj.
              description: "Username/Password Credentials for gitlab"
jenkins:
  systemMessage: "Controlled by Configuration as Code"
  numExecutors: 1
  quietPeriod: 0

  # Default LDAP configuration
  securityRealm:
    ldap:
      cache:
        size: 100
        ttl: 10
      configurations:
        - server: ldaps://ldap.corp.redhat.com
          rootDN: dc=redhat,dc=com
          inhibitInferRootDN: false
          userSearch: uid={0}
          groupSearchFilter: (& (cn={0}) (objectclass=GroupOfUniqueNames))
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseInsensitive

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "cci-octopus" # Instance telemetry collection
              - "ci-support" # Access for the support team
              - "sysops" # Access for the support team
              - "ccit-test" # OpenShift automation account
              - "ccit" # CCIT team
              - "sat-qe-jenkins"
          - name: "anonymous"
            description: "Anonymous users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "anonymous"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/ExtendedRead"
              - "View/Read"
            assignments:
              - "authenticated"
  clouds:
    - kubernetes:
        addMasterProxyEnvVars: true
        containerCapStr: "100"
        credentialsId: ""
        jenkinsTunnel: "satqe-jenkins.jenkins-csb-satellite-qe.svc:50000"
        jenkinsUrl: "http://satqe-jenkins.jenkins-csb-satellite-qe.svc:80"
        maxRequestsPerHostStr: "32"
        name: "upshift"
        namespace: "jenkins-csb-satellite-qe"
        serverCertificate: ${casc-secret/k8s-server-cert}
        serverUrl: "https://kubernetes.default.svc.cluster.local:443"
  globalNodeProperties:
    - envVars:
        env:
        - key: "satlab_tower_credentials_id"
          value: "ansible-tower-jenkins-user"
        - key: "satlab_tower_server"
          value: "Infra-Ansible-Tower-01"


  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  slaveAgentPort: 50000
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  updateCenter:
    sites:
    - id: "default"
      url: "http://do.not.install.plugins.manually.use.plugins.txt"

security:
  sSHD:
    port: 50022
  downloadSettings:
    useBrowser: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  shell:
    shell: "bash"
  ansibleTowerGlobalConfig:
    towerInstallation:
      - enableDebugging: true
        towerCredentialsId: ansible-tower-jenkins-user  # create these by hand in jenkins
        towerDisplayName: Infra-Ansible-Tower-01
        towerTrustCert: true
        towerURL: https://infra-ansible-tower-01.infra.sat.rdu2.redhat.com
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:\r\n\r\nCheck\
        \ console output at $BUILD_URL to view the results."
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultSuffix: "@redhat.com"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    smtpServer: "smtp.corp.redhat.com"
    useSsl: false
    watchingEnabled: false
  timestamperConfig:
    allPipelines: True
  globalLibraries:
    libraries:
      - defaultVersion: "master"
        name: "satqe_pipeline_lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://gitlab.sat.engineering.redhat.com/satelliteqe/satelliteqe-jenkins.git"
                traits:
                  - "gitBranchDiscovery"
  location:
    adminAddress: "SAT QE Jenkins Notifier <sat-qe-jenkins-notifier@redhat.com>"
  lockableResourcesManager:
    declaredResources:
      - name: "1001"
        description: "Subnet: 10.1.4.16/28, VLAN_ID:1001"
        labels: "vlan_pool"
      - name: "1002"
        description: "Subnet: 10.1.4.32/28, VLAN_ID:1002"
        labels: "vlan_pool"
      - name: "1015"
        description: "Subnet: 10.1.5.0/29, VLAN_ID:1015"
        labels: "vlan_pool"
      - name: "1016"
        description: "Subnet: 10.1.5.8/29, VLAN_ID:1016"
        labels: "vlan_pool"
      - name: "1017"
        description: "Subnet: 10.1.5.16/29, VLAN_ID:1017"
        labels: "vlan_pool"
      - name: "1018"
        description: "Subnet: 10.1.5.24/29, VLAN_ID:1018"
        labels: "vlan_pool"
      - name: "1019"
        description: "Subnet: 10.1.5.32/29, VLAN_ID:1019"
        labels: "vlan_pool"
      - name: "1020"
        description: "Subnet: 10.1.5.40/29, VLAN_ID:1020"
        labels: "vlan_pool"

configuration-as-code:
  deprecated: warn

jobs:
  - url: https://gitlab.sat.engineering.redhat.com/satelliteqe/satelliteqe-jenkins/raw/master/src/jobs/masterSeed.groovy
