# Broker settings
debug: False
inventory_file: "inventory.yaml"
# Host Settings
host_username: "root"
host_password: "<password>"
# Provider settings
AnsibleTower:
    base_url: "https://infra-ansible-tower-01.infra.sat.rdu2.redhat.com/"
    # Username AND password, OR an OAUTH token can be used for authentication
    username: "<username>"
    password: "<plain text password>"
    # token: "<AT personal access token>"
    release_workflow: "remove-vm"
    extend_workflow: "extend-vm"
    workflow_timeout: 7200
TestProvider:
    config_value: "something"
# You can set a nickname as a shortcut for arguments
nicks:
    # test_nick:
    #     test_action: "fake"
    #     arg1: "abc"
    #     arg2: 123
    #     arg3: True
