# Broker settings
debug: False
inventory_file: "inventory.yaml"
# Host Settings
host_username: "root"
host_password:
# Provider settings
AnsibleTower:
    instances:
      - production:
          base_url: "https://infra-ansible-tower-01.infra.sat.rdu2.redhat.com/"
          username: satqe_auto_droid
          password:
          default: True
          inventory: "satlab-rhv-02-inventory"
    release_workflow: "remove-vm"
    extend_workflow: "extend-vm"
    workflow_timeout: 7200
# You can set a nickname as a shortcut for arguments
nicks:
    rhel7:
        workflow: "deploy-base-rhel"
        rhel_version: "7.9"
    rhel7_fips:
        workflow: "deploy-base-rhel-fips"
        rhel_version: "7.9"
    rhel8:
        workflow: "deploy-base-rhel"
        rhel_version: "8.3"
    sat69:
        workflow: "deploy-sat-lite"
        deploy_sat_version: "6.9"
    cap69:
        workflow: "deploy-sat-capsule"
        deploy_sat_version: "6.9"
    rhel6:
        workflow: "deploy-base-rhel"
        rhel_version: "6.10"
